name: CI

on: 
  schedule:
    - cron: "15 14 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fetch upstream
      uses: tjusl/sync-upstream-repo@v0.1.6
      with:
        upstream_repo: https://github.com/BogdanDevUA/simple-ddos.git
        upstream_branch: master
        local_branch: master
	github_token: ${{ secrets.GITHUB_TOKEN }}
